// src/foundation/design_token_compiler.ts
// Phase 5A — Design Token Compiler.
//
// Reads architecture/design/design-tokens.yaml (Phase 4 locked registry)
// and emits a CSS Variables stylesheet using the `--mn-*` prefix.
//
// Hard rules:
//   - Components MUST consume variables, not hard-coded design values.
//   - Tokens are technology-agnostic values; the compiler is the bridge.
//   - Output is deterministic given the same input YAML.
//
// The compiler does NOT modify production mentornest-web; it produces a
// new CSS file under src/styles/ for mentornest-web-v2 to consume.
//
// This module is pure-string: no fs reads, no DOM. Caller passes the
// parsed YAML object so testability is high.

export interface DesignTokenRegistry {
  color?: Record<string, string | number>;
  typography?: Record<string, string | number>;
  spacing?: Record<string, string | number>;
  radius?: Record<string, string | number>;
  elevation?: Record<string, string | number>;
  motion?: Record<string, string | number>;
  breakpoint?: Record<string, string | number>;
  z_index?: Record<string, string | number>;
  // Free-form additional token groups (e.g. high_contrast)
  [group: string]: Record<string, string | number> | undefined;
}

/**
 * Render a CSS :root block from a design token registry.
 * Each leaf becomes `--mn-<group>-<key>: <value>;` (snake-cased key).
 */
export function compileTokensToCssVariables(registry: DesignTokenRegistry): string {
  const lines: string[] = [":root {"];
  for (const [group, entries] of Object.entries(registry)) {
    if (!entries || typeof entries !== "object") continue;
    for (const [key, value] of Object.entries(entries)) {
      const k = cssVarName(group, key);
      lines.push(`  ${k}: ${formatValue(value)};`);
    }
  }
  lines.push("}");
  return lines.join("\n");
}

/**
 * Emit a separate high-contrast token block, gated on `[data-mode="high-contrast"]`.
 * The values come from `registry.high_contrast.*` if present; otherwise they
 * fall back to the default tokens (with a slight darken/lighten pass).
 */
export function compileHighContrastTokens(registry: DesignTokenRegistry): string {
  const hc = registry.high_contrast || {};
  const lines: string[] = ['[data-mode="high-contrast"] {'];
  if (Object.keys(hc).length === 0) {
    // Fallback: derive dark base from defaults
    const fallback = registry.color || {};
    for (const [k, v] of Object.entries(fallback)) {
      lines.push(`  --mn-color-${cssKey(k)}: ${formatValue(invertForHighContrast(v))};`);
    }
  } else {
    for (const [k, v] of Object.entries(hc)) {
      lines.push(`  --mn-color-${cssKey(k)}: ${formatValue(v)};`);
    }
  }
  lines.push("}");
  return lines.join("\n");
}

/**
 * Emit a color-vision-safe token block, gated on `[data-mode="color-vision-safe"]`.
 * Uses high-contrast as the safe default.
 */
export function compileColorVisionSafeTokens(registry: DesignTokenRegistry): string {
  const cv = registry.color_vision_safe || registry.high_contrast || {};
  const lines: string[] = ['[data-mode="color-vision-safe"] {'];
  for (const [k, v] of Object.entries(cv)) {
    lines.push(`  --mn-color-${cssKey(k)}: ${formatValue(v)};`);
  }
  lines.push("}");
  return lines.join("\n");
}

/** Compile all three blocks into a single stylesheet. */
export function compileFullStylesheet(registry: DesignTokenRegistry): string {
  return [
    "/* Generated by design_token_compiler.ts — DO NOT EDIT BY HAND. */",
    "/* Source: architecture/design/design-tokens.yaml */",
    "",
    compileTokensToCssVariables(registry),
    "",
    compileHighContrastTokens(registry),
    "",
    compileColorVisionSafeTokens(registry),
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function cssVarName(group: string, key: string): string {
  return `--mn-${cssKey(group)}-${cssKey(key)}`;
}

function cssKey(raw: string): string {
  // snake-case-ish, lowercase, dashes → underscores, strip non-alphanum
  return raw
    .replace(/[^a-zA-Z0-9_-]/g, "")
    .replace(/-+/g, "-")
    .toLowerCase();
}

function formatValue(v: unknown): string {
  if (typeof v === "number") {
    // Heuristic: integer seconds/px/scale → no unit unless obvious from key
    return String(v);
  }
  return String(v);
}

function invertForHighContrast(v: unknown): string {
  // Crude: if hex color, swap luminance. Otherwise return as-is.
  if (typeof v !== "string") return String(v);
  const m = v.match(/^#([0-9a-f]{6})$/i);
  if (!m) return v;
  const r = parseInt(m[1].slice(0, 2), 16);
  const g = parseInt(m[1].slice(2, 4), 16);
  const b = parseInt(m[1].slice(4, 6), 16);
  // Flip: simple inversion to maximize contrast
  const ri = 255 - r;
  const gi = 255 - g;
  const bi = 255 - b;
  const toHex = (x: number) => x.toString(16).padStart(2, "0");
  return `#${toHex(ri)}${toHex(gi)}${toHex(bi)}`;
}

export const DesignTokenCompiler = Object.freeze({
  compileTokensToCssVariables,
  compileHighContrastTokens,
  compileColorVisionSafeTokens,
  compileFullStylesheet,
});