// src/foundation/design_token_compiler.mjs
// Phase 5A — Design Token Compiler.

export function compileTokensToCssVariables(registry) {
  const lines = [":root {"];
  for (const [group, entries] of Object.entries(registry)) {
    if (!entries || typeof entries !== "object") continue;
    for (const [key, value] of Object.entries(entries)) {
      const k = cssVarName(group, key);
      lines.push(`  ${k}: ${formatValue(value)};`);
    }
  }
  lines.push("}");
  return lines.join("\n");
}

export function compileHighContrastTokens(registry) {
  const hc = registry.high_contrast || {};
  const lines = ['[data-mode="high-contrast"] {'];
  if (Object.keys(hc).length === 0) {
    const fallback = registry.color || {};
    for (const [k, v] of Object.entries(fallback)) {
      lines.push(`  --mn-color-${cssKey(k)}: ${formatValue(invertForHighContrast(v))};`);
    }
  } else {
    for (const [k, v] of Object.entries(hc)) {
      lines.push(`  --mn-color-${cssKey(k)}: ${formatValue(v)};`);
    }
  }
  lines.push("}");
  return lines.join("\n");
}

export function compileColorVisionSafeTokens(registry) {
  const cv = registry.color_vision_safe || registry.high_contrast || {};
  const lines = ['[data-mode="color-vision-safe"] {'];
  for (const [k, v] of Object.entries(cv)) {
    lines.push(`  --mn-color-${cssKey(k)}: ${formatValue(v)};`);
  }
  lines.push("}");
  return lines.join("\n");
}

export function compileFullStylesheet(registry) {
  return [
    "/* Generated by design_token_compiler.mjs — DO NOT EDIT BY HAND. */",
    "/* Source: architecture/design/design-tokens.yaml */",
    "",
    compileTokensToCssVariables(registry),
    "",
    compileHighContrastTokens(registry),
    "",
    compileColorVisionSafeTokens(registry),
    "",
  ].join("\n");
}

function cssVarName(group, key) {
  return `--mn-${cssKey(group)}-${cssKey(key)}`;
}

function cssKey(raw) {
  return raw
    .replace(/[^a-zA-Z0-9_-]/g, "")
    .replace(/-+/g, "-")
    .toLowerCase();
}

function formatValue(v) {
  if (typeof v === "number") return String(v);
  return String(v);
}

function invertForHighContrast(v) {
  if (typeof v !== "string") return String(v);
  const m = v.match(/^#([0-9a-f]{6})$/i);
  if (!m) return v;
  const r = parseInt(m[1].slice(0, 2), 16);
  const g = parseInt(m[1].slice(2, 4), 16);
  const b = parseInt(m[1].slice(4, 6), 16);
  const toHex = (x) => x.toString(16).padStart(2, "0");
  return `#${toHex(255 - r)}${toHex(255 - g)}${toHex(255 - b)}`;
}

export const DesignTokenCompiler = Object.freeze({
  compileTokensToCssVariables,
  compileHighContrastTokens,
  compileColorVisionSafeTokens,
  compileFullStylesheet,
});