import {lookupScienceErrorCode} from "./science_error_taxonomy.mjs"; import {classifyScienceSubskill} from "./science_subskill_map.mjs";
const norm=s=>String(s??"").toLowerCase().replace(/\s+/g,"").replace(/[。．，、,.!?！？；;：:（）()]/g,"");
function infer({student_answer,expected_answer,kp,mode="written"}){const sub=classifyScienceSubskill({knowledge_point:kp}).primary_subskill;if(!String(student_answer??"").trim())return ["SCI-METH-READING"];if(/相關|造成|因為|所以/.test(String(student_answer)))return ["SCI-CAUSAL-CORRELATION"];if(/圖表|增加|減少|趨勢|比例|單位/.test(String(student_answer)))return sub==="data_interpretation"?["SCI-DATA-AXIS"]:["SCI-DATA-RATIO"];if(/實驗|控制組|實驗組|變因/.test(String(student_answer)))return ["SCI-METH-MANIPULATE"];return sub==="safety"?["SCI-SAFETY-LABEL"]:"SCI-CON-DISCIPLINE";}
export function emitEvidence(input={}){if(!input.student_id)throw new Error("emitEvidence: student_id required");return {schema_version:"science-specialist-evidence-v1",emitted_at:new Date().toISOString(),emitted_by:input.emitted_by||"science-specialist",student_id:input.student_id,subject:"science",knowledge_point:input.knowledge_point||"",subskill:input.subskill||"",error_codes:Array.isArray(input.error_codes)?input.error_codes:[],result:input.result||null,diagnosis:input.diagnosis||null};}
export function diagnoseScienceResponse(input){input=input||{};const expected=norm(input.expected_answer),student=norm(input.student_answer),correct=expected.length>0&&expected===student,valid=!!input.expected_answer||!!input.student_answer, codes=correct?[]:infer(input),entry=codes[0]?lookupScienceErrorCode(codes[0]):null, level=correct?0:1;return {valid,correct,error_codes:codes,hint_level:level,hint_text_zh:correct?"答對了！":entry?.hint_template||"請再檢查題目條件。",mini_lesson_suggested:!correct,mastery_check_suggested:!correct,evidence_payload:emitEvidence({student_id:input.student_id||"student_unknown",knowledge_point:input.knowledge_point,error_codes:codes,result:correct?"correct":"incorrect",diagnosis:{mode:input.mode||"written",grade:input.grade??null}}),diagnosis_payload:{schema_version:"science-specialist-diagnosis-v1",student_id:input.student_id||"student_unknown",knowledge_point:input.knowledge_point||"",error_codes:codes,recommendation_zh:entry?.mini_lesson_hint||null,subskill:classifyScienceSubskill({knowledge_point:input.knowledge_point||""}).primary_subskill}};}
export function analyzeExperiment(input){input=input||{};const vars=input.variables||{}, expected=input.expected_design||{}, missing=["independent","dependent","controlled"].filter(k=>!vars[k]);const errors=[];if(!vars.independent||!expected.independent)errors.push("SCI-METH-MANIPULATE");if(!vars.controlled||!expected.controlled)errors.push("SCI-CAUSAL-CONTROL");return {correct:errors.length===0,missing_variables:missing,errors,evidence_payload:emitEvidence({student_id:input.student_id||"student_unknown",knowledge_point:input.knowledge_point,error_codes:errors})};}
export function interpretChartTable(input){input=input||{};const correct=norm(input.student_answer)===norm(input.expected_answer),error=correct?[]:["SCI-DATA-AXIS"];return {correct,reasoning_steps:["確認橫軸與縱軸","確認單位與刻度","比較資料趨勢"],error_codes:error,hint_text_zh:correct?"圖表判讀正確。":"先確認圖表的軸線、單位與刻度，再讀取答案。",evidence_payload:emitEvidence({student_id:input.student_id||"student_unknown",error_codes:error})};}
export function interpretDiagram(input){input=input||{};const descriptor=input.diagram_descriptor||{}, expected=Array.isArray(input.expected_answer)?input.expected_answer:[input.expected_answer].filter(Boolean),student=String(input.student_answer||""),matched=expected.filter(x=>student.includes(String(x))),missed=expected.filter(x=>!student.includes(String(x)));return {correct:missed.length===0,matched_elements:matched,missed_elements:missed,error_codes:missed.length?["SCI-DIAG-LEGEND"]:[]};}
export function scienceSpecialistDecide(input={}){const sub=classifyScienceSubskill({knowledge_point:input.knowledge_point||""}).primary_subskill,attempts=Number(input.attempts)||1,mastery=Number(input.mastery);let action=sub==="experiment"?"experiment_simulation":sub==="data_interpretation"?"chart_drilling":sub==="diagram"?"diagram_explanation":mastery>=.8?"mastery_check":attempts>=3?"concept_clarification":"text_prompt";return {action,rationale:`subskill=${sub}; attempts=${attempts}; mastery=${input.mastery??"unknown"}`};}
