// test/foundation/design_token_compiler.test.mjs
// Phase 5A — design_token_compiler unit tests.

import { test } from "node:test";
import assert from "node:assert/strict";
import {
  compileTokensToCssVariables,
  compileHighContrastTokens,
  compileColorVisionSafeTokens,
  compileFullStylesheet,
  DesignTokenCompiler,
} from "../../src/foundation/design_token_compiler.mjs";

const sampleRegistry = {
  color: {
    primary: "#2266dd",
    text: "#222222",
    bg: "#ffffff",
  },
  typography: {
    base_font_px: 16,
    heading_font_px: 24,
  },
  spacing: {
    sm: "8px",
    md: "16px",
    lg: "24px",
  },
};

test("compiler: emits :root block with --mn-* prefixed vars", () => {
  const css = compileTokensToCssVariables(sampleRegistry);
  assert.match(css, /:root \{/);
  assert.match(css, /--mn-color-primary: #2266dd;/);
  assert.match(css, /--mn-typography-base_font_px: 16;/);
  assert.match(css, /--mn-spacing-md: 16px;/);
  assert.match(css, /\}/);
});

test("compiler: every group emitted under --mn-<group>-", () => {
  const css = compileTokensToCssVariables(sampleRegistry);
  assert.match(css, /--mn-color-/);
  assert.match(css, /--mn-typography-/);
  assert.match(css, /--mn-spacing-/);
});

test("compiler: keys are snake_cased in CSS output", () => {
  const css = compileTokensToCssVariables({ color: { "base-bg": "#fff" } });
  assert.match(css, /--mn-color-base-bg:/);
});

test("compiler: high_contrast block gated by [data-mode]", () => {
  const css = compileHighContrastTokens(sampleRegistry);
  assert.match(css, /\[data-mode="high-contrast"\]/);
  assert.match(css, /\{/);
});

test("compiler: high_contrast uses provided high_contrast registry if present", () => {
  const reg = { ...sampleRegistry, high_contrast: { primary: "#ffffff" } };
  const css = compileHighContrastTokens(reg);
  assert.match(css, /--mn-color-primary: #ffffff;/);
});

test("compiler: high_contrast falls back to inverted defaults when no high_contrast block", () => {
  const css = compileHighContrastTokens(sampleRegistry);
  // Inverted color for primary (#2266dd → inverted)
  assert.match(css, /--mn-color-primary: /);
  // value should NOT equal the default's #2266dd (it was inverted)
  assert.ok(!/--mn-color-primary: #2266dd;/.test(css));
});

test("compiler: color_vision_safe block gated by [data-mode]", () => {
  const css = compileColorVisionSafeTokens(sampleRegistry);
  assert.match(css, /\[data-mode="color-vision-safe"\]/);
});

test("compiler: color_vision_safe falls back to high_contrast if no separate block", () => {
  const css = compileColorVisionSafeTokens(sampleRegistry);
  assert.ok(css.length > 0);
});

test("compiler: compileFullStylesheet emits all three blocks", () => {
  const css = compileFullStylesheet(sampleRegistry);
  assert.match(css, /:root \{/);
  assert.match(css, /\[data-mode="high-contrast"\]/);
  assert.match(css, /\[data-mode="color-vision-safe"\]/);
  assert.match(css, /Generated by design_token_compiler/);
});

test("compiler: handles numeric values (no units unless provided)", () => {
  const css = compileTokensToCssVariables({ typography: { base: 16 } });
  assert.match(css, /--mn-typography-base: 16;/);
});

test("compiler: empty registry emits empty :root block", () => {
  const css = compileTokensToCssVariables({});
  // Just :root with opening + closing braces (possibly with newline)
  assert.match(css, /:root\s*\{[^}]*\}/);
});

test("compiler: same input → same output (deterministic)", () => {
  const a = compileTokensToCssVariables(sampleRegistry);
  const b = compileTokensToCssVariables(sampleRegistry);
  assert.equal(a, b);
});

test("compiler: DesignTokenCompiler namespace", () => {
  assert.equal(typeof DesignTokenCompiler.compileFullStylesheet, "function");
  assert.equal(typeof DesignTokenCompiler.compileTokensToCssVariables, "function");
  assert.equal(typeof DesignTokenCompiler.compileHighContrastTokens, "function");
  assert.equal(typeof DesignTokenCompiler.compileColorVisionSafeTokens, "function");
});

test("compiler: real design-tokens.yaml snippet compiles without throwing", () => {
  // Sample shape pulled from architecture/design/design-tokens.yaml header
  const real = {
    color: { "primary-500": "#2266DD", "neutral-900": "#111111", "success-500": "#2BAB66", "warning-500": "#E5A82E", "danger-500": "#D94545" },
    typography: { "font-size-base": 16, "line-height-base": 1.5 },
    spacing: { "space-1": "4px", "space-2": "8px", "space-3": "16px" },
    radius: { "radius-sm": "4px", "radius-md": "8px" },
  };
  const css = compileFullStylesheet(real);
  assert.ok(css.includes("--mn-color-primary-500: #2266DD;"));
  assert.ok(css.includes("--mn-spacing-space-3: 16px;"));
});